# Generated by Django 4.2.11 on 2024-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True)),
                ('degree', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('freelance', models.BooleanField()),
            ],
        ),
    ]
