# Generated by Django 4.2.11 on 2024-04-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='filter',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
