# Generated by Django 4.2.11 on 2024-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langage', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
